2022-05-17 22:45:40,266 - werkzeug - INFO -  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
2022-05-17 22:46:52,125 - werkzeug - INFO - 127.0.0.1 - - [17/May/2022 22:46:52] "GET / HTTP/1.1" 200 -
2022-05-17 22:46:54,579 - werkzeug - INFO - 127.0.0.1 - - [17/May/2022 22:46:54] "GET / HTTP/1.1" 200 -
2022-05-17 22:46:55,445 - werkzeug - INFO - 127.0.0.1 - - [17/May/2022 22:46:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-05-17 22:59:43,215 - werkzeug - INFO - 127.0.0.1 - - [17/May/2022 22:59:43] "GET / HTTP/1.1" 200 -
2022-05-17 22:59:45,056 - werkzeug - INFO - 127.0.0.1 - - [17/May/2022 22:59:45] "GET / HTTP/1.1" 200 -
2022-05-17 22:59:46,003 - werkzeug - INFO - 127.0.0.1 - - [17/May/2022 22:59:46] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-05-18 12:02:07,810 - werkzeug - INFO -  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
2022-05-18 12:02:27,365 - werkzeug - INFO - 127.0.0.1 - - [18/May/2022 12:02:27] "GET / HTTP/1.1" 200 -
2022-05-18 12:02:27,641 - werkzeug - INFO - 127.0.0.1 - - [18/May/2022 12:02:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-05-18 12:02:43,615 - werkzeug - INFO -  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
2022-05-18 12:02:44,408 - werkzeug - INFO - 127.0.0.1 - - [18/May/2022 12:02:44] "GET / HTTP/1.1" 200 -
2022-05-21 22:48:56,803 - werkzeug - INFO -  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
2022-05-21 22:49:08,476 - main - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:/Users/miaf2/PycharmProjects/bots/sait_for_tg_bot/main.py", line 14, in start
    return render_template('button.html')
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\miaf2\PycharmProjects\bots\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\miaf2\PycharmProjects\bots\sait_for_tg_bot\templates\button.html", line 17, in template
    <button disabled></button> }}</p>
jinja2.exceptions.TemplateSyntaxError: expected name or number
2022-05-21 22:49:08,501 - werkzeug - INFO - 127.0.0.1 - - [21/May/2022 22:49:08] "[35m[1mGET / HTTP/1.1[0m" 500 -
2022-05-21 22:49:09,223 - werkzeug - INFO - 127.0.0.1 - - [21/May/2022 22:49:09] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
